name: Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOCKER_FLAGS: ""
  CI: 1

jobs:
  gcc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: test with gcc
        run: rake docker_test_gcc
  clang:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: test with clang
        run: rake docker_test_clang
  ruby27:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: test when hosted by Ruby 2.7
        run: rake docker_test_ruby27
  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      - name: checkout submodules
        run: git submodule update --init --recursive
      - name: install ruby
        run: brew install ruby autoconf automake libtool
      - name: install openssl
        run: brew install openssl
      - name: test with clang on macOS
        run: |
          pkg_env=$(brew info openssl | grep PKG_CONFIG_PATH | sed 's/"//g')
          $pkg_env
          rake test
